name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        cd server
        npm install
        
    - name: Run tests
      run: |
        cd server
        npm test
      env:
        NODE_ENV: test
        MONGODB_URI: mongodb://localhost:27017/test
        JWT_SECRET: test_secret
        STRIPE_SECRET_KEY: test_key

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Debug Docker Hub credentials
      run: |
        echo "Docker Hub username: ${{ secrets.DOCKERHUB_USERNAME }}"
        echo "Docker Hub token length: ${#DOCKERHUB_TOKEN}"
        echo "Repository name: ${{ secrets.DOCKERHUB_USERNAME }}/anti-procrastination-frontend"
        
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        registry: docker.io
        
    - name: Verify Docker login
      run: |
        docker info
        docker images
        
    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./src/Dockerfile
        push: true
        tags: |
          docker.io/${{ secrets.DOCKERHUB_USERNAME }}/anti-procrastination-frontend:latest
          docker.io/${{ secrets.DOCKERHUB_USERNAME }}/anti-procrastination-frontend:${{ github.sha }}
        build-args: |
          NODE_ENV=production
        
    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: ./server
        file: ./server/Dockerfile
        push: true
        tags: |
          docker.io/${{ secrets.DOCKERHUB_USERNAME }}/anti-procrastination-backend:latest
          docker.io/${{ secrets.DOCKERHUB_USERNAME }}/anti-procrastination-backend:${{ github.sha }} 